from dataclasses import dataclass, field
from typing import Dict, Optional
import time


@dataclass
class License:
    """
    Core license entity (source of truth in server DB)
    """

    license_key: str
    user_id: str

    plan: str  # free / basic / pro / enterprise

    expire_at: int

    status: str = "active"  # active / expired / revoked

    machine_id: Optional[str] = None

    # feature snapshot (generated by FeatureService)
    features: Dict[str, dict] = field(default_factory=dict)

    created_at: int = field(default_factory=lambda: int(time.time()))
    updated_at: int = field(default_factory=lambda: int(time.time()))

    def is_expired(self, now: Optional[int] = None) -> bool:
        now = now or int(time.time())
        return now > self.expire_at

    def is_active(self) -> bool:
        return self.status == "active"

    def is_revoked(self) -> bool:
        return self.status == "revoked"

    def can_use_machine(self, machine_id: str) -> bool:
        """
        Check machine binding
        """
        if not self.machine_id:
            return True

        return self.machine_id == machine_id

    def bind_machine(self, machine_id: str):
        """
        Bind first device
        """
        if not self.machine_id:
            self.machine_id = machine_id
            self.updated_at = int(time.time())